[tool.poetry]
name = "pgbackend"
version = "0.1.0"
description = "Django database backend for psycopg3"
authors = ["pwtail <abvit89s@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pgbackend" },
]

[tool.poetry.dependencies]
python = "^3.10"
psycopg = {extras = ["pool"], version = "^3.1.4"}
django = {git = "https://github.com/apollo13/django.git", rev = "psycopg3"}
greenhack = {git = "https://github.com/Bi-Coloured-Python-Rock-Snake/greenhack.git"}


[tool.poetry.group.dev.dependencies]
httpx = "^0.23.0"
channels = "^4.0.0"
uvicorn = {extras = ["standard"], version = "^0.19.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
