# Generated by Django 4.2.dev20220924161115 on 2022-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
