# Generated by Django 4.2.dev20220924161115 on 2022-10-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cubicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='cubicle.souslik'),
        ),
    ]
