# Generated by Django 4.2.dev20220924161115 on 2022-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubicle', '0002_souslik_cubicle_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
